# APIs Lab

In this lab, you will work with different APIs to build datasets and perform basic analysis.

The goal is to practice how to:

- Make API requests  
- Explore JSON responses  
- Extract relevant information  
- Transform data into pandas DataFrames  
- Generate simple insights  

You will work like a data analyst using APIs data.

# Challenge 1: Pokémon Dataset & Analysis

## Goal

Build and analyze a Pokémon dataset using the API.

## Example (single request)

Below you can see how to get data for ONE Pokémon:

In [1]:
import requests
poke_list = []
poke_dict = {}

for id in range (1,10):
    url = f"https://pokeapi.co/api/v2/pokemon/{id}"
    print(url)

    response = requests.get(url)
    data = response.json()

    for key,value in data.items():
        if key == "name":
            poke_dict[key] = value
        if key == "height":
            poke_dict[key] = value
        if key == "weight":
            poke_dict[key] = value
            #poke_dict.append({key,value})
        if key == "base_experience":
            poke_dict[key] = value
            #poke_dict.append({key,value})
        if key =="types":
            type =((value)[0]['type']['name'])
            poke_dict[key] = type

https://pokeapi.co/api/v2/pokemon/1
https://pokeapi.co/api/v2/pokemon/2
https://pokeapi.co/api/v2/pokemon/3
https://pokeapi.co/api/v2/pokemon/4
https://pokeapi.co/api/v2/pokemon/5
https://pokeapi.co/api/v2/pokemon/6
https://pokeapi.co/api/v2/pokemon/7
https://pokeapi.co/api/v2/pokemon/8
https://pokeapi.co/api/v2/pokemon/9

In [22]:
import requests
poke_list = []

import requests

poke_list = []

for id in range(1, 151):
    url = f"https://pokeapi.co/api/v2/pokemon/{id}"
    response = requests.get(url)
    data = response.json()

    poke_type = data["types"][0]["type"]["name"]

    poke_list.append({
        "name": data["name"],
        "height": data["height"],
        "weight": data["weight"],
        "base_experience": data["base_experience"],
        "type": poke_type
    })

print(poke_list)

[{'name': 'bulbasaur', 'height': 7, 'weight': 69, 'base_experience': 64, 'type': 'grass'}, {'name': 'ivysaur', 'height': 10, 'weight': 130, 'base_experience': 142, 'type': 'grass'}, {'name': 'venusaur', 'height': 20, 'weight': 1000, 'base_experience': 236, 'type': 'grass'}, {'name': 'charmander', 'height': 6, 'weight': 85, 'base_experience': 62, 'type': 'fire'}, {'name': 'charmeleon', 'height': 11, 'weight': 190, 'base_experience': 142, 'type': 'fire'}, {'name': 'charizard', 'height': 17, 'weight': 905, 'base_experience': 240, 'type': 'fire'}, {'name': 'squirtle', 'height': 5, 'weight': 90, 'base_experience': 63, 'type': 'water'}, {'name': 'wartortle', 'height': 10, 'weight': 225, 'base_experience': 142, 'type': 'water'}, {'name': 'blastoise', 'height': 16, 'weight': 855, 'base_experience': 239, 'type': 'water'}, {'name': 'caterpie', 'height': 3, 'weight': 29, 'base_experience': 39, 'type': 'bug'}, {'name': 'metapod', 'height': 7, 'weight': 99, 'base_experience': 72, 'type': 'bug'}, {'name': 'butterfree', 'height': 11, 'weight': 320, 'base_experience': 178, 'type': 'bug'}, {'name': 'weedle', 'height': 3, 'weight': 32, 'base_experience': 39, 'type': 'bug'}, {'name': 'kakuna', 'height': 6, 'weight': 100, 'base_experience': 72, 'type': 'bug'}, {'name': 'beedrill', 'height': 10, 'weight': 295, 'base_experience': 178, 'type': 'bug'}, {'name': 'pidgey', 'height': 3, 'weight': 18, 'base_experience': 50, 'type': 'normal'}, {'name': 'pidgeotto', 'height': 11, 'weight': 300, 'base_experience': 122, 'type': 'normal'}, {'name': 'pidgeot', 'height': 15, 'weight': 395, 'base_experience': 216, 'type': 'normal'}, {'name': 'rattata', 'height': 3, 'weight': 35, 'base_experience': 51, 'type': 'normal'}, {'name': 'raticate', 'height': 7, 'weight': 185, 'base_experience': 145, 'type': 'normal'}, {'name': 'spearow', 'height': 3, 'weight': 20, 'base_experience': 52, 'type': 'normal'}, {'name': 'fearow', 'height': 12, 'weight': 380, 'base_experience': 155, 'type': 'normal'}, {'name': 'ekans', 'height': 20, 'weight': 69, 'base_experience': 58, 'type': 'poison'}, {'name': 'arbok', 'height': 35, 'weight': 650, 'base_experience': 157, 'type': 'poison'}, {'name': 'pikachu', 'height': 4, 'weight': 60, 'base_experience': 112, 'type': 'electric'}, {'name': 'raichu', 'height': 8, 'weight': 300, 'base_experience': 218, 'type': 'electric'}, {'name': 'sandshrew', 'height': 6, 'weight': 120, 'base_experience': 60, 'type': 'ground'}, {'name': 'sandslash', 'height': 10, 'weight': 295, 'base_experience': 158, 'type': 'ground'}, {'name': 'nidoran-f', 'height': 4, 'weight': 70, 'base_experience': 55, 'type': 'poison'}, {'name': 'nidorina', 'height': 8, 'weight': 200, 'base_experience': 128, 'type': 'poison'}, {'name': 'nidoqueen', 'height': 13, 'weight': 600, 'base_experience': 227, 'type': 'poison'}, {'name': 'nidoran-m', 'height': 5, 'weight': 90, 'base_experience': 55, 'type': 'poison'}, {'name': 'nidorino', 'height': 9, 'weight': 195, 'base_experience': 128, 'type': 'poison'}, {'name': 'nidoking', 'height': 14, 'weight': 620, 'base_experience': 227, 'type': 'poison'}, {'name': 'clefairy', 'height': 6, 'weight': 75, 'base_experience': 113, 'type': 'fairy'}, {'name': 'clefable', 'height': 13, 'weight': 400, 'base_experience': 217, 'type': 'fairy'}, {'name': 'vulpix', 'height': 6, 'weight': 99, 'base_experience': 60, 'type': 'fire'}, {'name': 'ninetales', 'height': 11, 'weight': 199, 'base_experience': 177, 'type': 'fire'}, {'name': 'jigglypuff', 'height': 5, 'weight': 55, 'base_experience': 95, 'type': 'normal'}, {'name': 'wigglytuff', 'height': 10, 'weight': 120, 'base_experience': 196, 'type': 'normal'}, {'name': 'zubat', 'height': 8, 'weight': 75, 'base_experience': 49, 'type': 'poison'}, {'name': 'golbat', 'height': 16, 'weight': 550, 'base_experience': 159, 'type': 'poison'}, {'name': 'oddish', 'height': 5, 'weight': 54, 'base_experience': 64, 'type': 'grass'}, {'name': 'gloom', 'height': 8, 'weight': 86, 'base_experience': 138, 'type': 'grass'}, {'name': 'vileplume', 'height': 12, 'weight': 186, 'base_experience': 221, 'type': 'grass'}, {'name': 'paras', 'height': 3, 'weight': 54, 'base_experience': 57, 'type': 'bug'}, {'name': 'parasect', 'height': 10, 'weight': 295, 'base_experience': 142, 'type': 'bug'}, {'name': 'venonat', 'height': 10, 'weight': 300, 'base_experience': 61, 'type': 'bug'}, {'name': 'venomoth', 'height': 15, 'weight': 125, 'base_experience': 158, 'type': 'bug'}, {'name': 'diglett', 'height': 2, 'weight': 8, 'base_experience': 53, 'type': 'ground'}, {'name': 'dugtrio', 'height': 7, 'weight': 333, 'base_experience': 149, 'type': 'ground'}, {'name': 'meowth', 'height': 4, 'weight': 42, 'base_experience': 58, 'type': 'normal'}, {'name': 'persian', 'height': 10, 'weight': 320, 'base_experience': 154, 'type': 'normal'}, {'name': 'psyduck', 'height': 8, 'weight': 196, 'base_experience': 64, 'type': 'water'}, {'name': 'golduck', 'height': 17, 'weight': 766, 'base_experience': 175, 'type': 'water'}, {'name': 'mankey', 'height': 5, 'weight': 280, 'base_experience': 61, 'type': 'fighting'}, {'name': 'primeape', 'height': 10, 'weight': 320, 'base_experience': 159, 'type': 'fighting'}, {'name': 'growlithe', 'height': 7, 'weight': 190, 'base_experience': 70, 'type': 'fire'}, {'name': 'arcanine', 'height': 19, 'weight': 1550, 'base_experience': 194, 'type': 'fire'}, {'name': 'poliwag', 'height': 6, 'weight': 124, 'base_experience': 60, 'type': 'water'}, {'name': 'poliwhirl', 'height': 10, 'weight': 200, 'base_experience': 135, 'type': 'water'}, {'name': 'poliwrath', 'height': 13, 'weight': 540, 'base_experience': 230, 'type': 'water'}, {'name': 'abra', 'height': 9, 'weight': 195, 'base_experience': 62, 'type': 'psychic'}, {'name': 'kadabra', 'height': 13, 'weight': 565, 'base_experience': 140, 'type': 'psychic'}, {'name': 'alakazam', 'height': 15, 'weight': 480, 'base_experience': 225, 'type': 'psychic'}, {'name': 'machop', 'height': 8, 'weight': 195, 'base_experience': 61, 'type': 'fighting'}, {'name': 'machoke', 'height': 15, 'weight': 705, 'base_experience': 142, 'type': 'fighting'}, {'name': 'machamp', 'height': 16, 'weight': 1300, 'base_experience': 227, 'type': 'fighting'}, {'name': 'bellsprout', 'height': 7, 'weight': 40, 'base_experience': 60, 'type': 'grass'}, {'name': 'weepinbell', 'height': 10, 'weight': 64, 'base_experience': 137, 'type': 'grass'}, {'name': 'victreebel', 'height': 17, 'weight': 155, 'base_experience': 221, 'type': 'grass'}, {'name': 'tentacool', 'height': 9, 'weight': 455, 'base_experience': 67, 'type': 'water'}, {'name': 'tentacruel', 'height': 16, 'weight': 550, 'base_experience': 180, 'type': 'water'}, {'name': 'geodude', 'height': 4, 'weight': 200, 'base_experience': 60, 'type': 'rock'}, {'name': 'graveler', 'height': 10, 'weight': 1050, 'base_experience': 137, 'type': 'rock'}, {'name': 'golem', 'height': 14, 'weight': 3000, 'base_experience': 223, 'type': 'rock'}, {'name': 'ponyta', 'height': 10, 'weight': 300, 'base_experience': 82, 'type': 'fire'}, {'name': 'rapidash', 'height': 17, 'weight': 950, 'base_experience': 175, 'type': 'fire'}, {'name': 'slowpoke', 'height': 12, 'weight': 360, 'base_experience': 63, 'type': 'water'}, {'name': 'slowbro', 'height': 16, 'weight': 785, 'base_experience': 172, 'type': 'water'}, {'name': 'magnemite', 'height': 3, 'weight': 60, 'base_experience': 65, 'type': 'electric'}, {'name': 'magneton', 'height': 10, 'weight': 600, 'base_experience': 163, 'type': 'electric'}, {'name': 'farfetchd', 'height': 8, 'weight': 150, 'base_experience': 132, 'type': 'normal'}, {'name': 'doduo', 'height': 14, 'weight': 392, 'base_experience': 62, 'type': 'normal'}, {'name': 'dodrio', 'height': 18, 'weight': 852, 'base_experience': 165, 'type': 'normal'}, {'name': 'seel', 'height': 11, 'weight': 900, 'base_experience': 65, 'type': 'water'}, {'name': 'dewgong', 'height': 17, 'weight': 1200, 'base_experience': 166, 'type': 'water'}, {'name': 'grimer', 'height': 9, 'weight': 300, 'base_experience': 65, 'type': 'poison'}, {'name': 'muk', 'height': 12, 'weight': 300, 'base_experience': 175, 'type': 'poison'}, {'name': 'shellder', 'height': 3, 'weight': 40, 'base_experience': 61, 'type': 'water'}, {'name': 'cloyster', 'height': 15, 'weight': 1325, 'base_experience': 184, 'type': 'water'}, {'name': 'gastly', 'height': 13, 'weight': 1, 'base_experience': 62, 'type': 'ghost'}, {'name': 'haunter', 'height': 16, 'weight': 1, 'base_experience': 142, 'type': 'ghost'}, {'name': 'gengar', 'height': 15, 'weight': 405, 'base_experience': 225, 'type': 'ghost'}, {'name': 'onix', 'height': 88, 'weight': 2100, 'base_experience': 77, 'type': 'rock'}, {'name': 'drowzee', 'height': 10, 'weight': 324, 'base_experience': 66, 'type': 'psychic'}, {'name': 'hypno', 'height': 16, 'weight': 756, 'base_experience': 169, 'type': 'psychic'}, {'name': 'krabby', 'height': 4, 'weight': 65, 'base_experience': 65, 'type': 'water'}, {'name': 'kingler', 'height': 13, 'weight': 600, 'base_experience': 166, 'type': 'water'}, {'name': 'voltorb', 'height': 5, 'weight': 104, 'base_experience': 66, 'type': 'electric'}, {'name': 'electrode', 'height': 12, 'weight': 666, 'base_experience': 172, 'type': 'electric'}, {'name': 'exeggcute', 'height': 4, 'weight': 25, 'base_experience': 65, 'type': 'grass'}, {'name': 'exeggutor', 'height': 20, 'weight': 1200, 'base_experience': 186, 'type': 'grass'}, {'name': 'cubone', 'height': 4, 'weight': 65, 'base_experience': 64, 'type': 'ground'}, {'name': 'marowak', 'height': 10, 'weight': 450, 'base_experience': 149, 'type': 'ground'}, {'name': 'hitmonlee', 'height': 15, 'weight': 498, 'base_experience': 159, 'type': 'fighting'}, {'name': 'hitmonchan', 'height': 14, 'weight': 502, 'base_experience': 159, 'type': 'fighting'}, {'name': 'lickitung', 'height': 12, 'weight': 655, 'base_experience': 77, 'type': 'normal'}, {'name': 'koffing', 'height': 6, 'weight': 10, 'base_experience': 68, 'type': 'poison'}, {'name': 'weezing', 'height': 12, 'weight': 95, 'base_experience': 172, 'type': 'poison'}, {'name': 'rhyhorn', 'height': 10, 'weight': 1150, 'base_experience': 69, 'type': 'ground'}, {'name': 'rhydon', 'height': 19, 'weight': 1200, 'base_experience': 170, 'type': 'ground'}, {'name': 'chansey', 'height': 11, 'weight': 346, 'base_experience': 395, 'type': 'normal'}, {'name': 'tangela', 'height': 10, 'weight': 350, 'base_experience': 87, 'type': 'grass'}, {'name': 'kangaskhan', 'height': 22, 'weight': 800, 'base_experience': 172, 'type': 'normal'}, {'name': 'horsea', 'height': 4, 'weight': 80, 'base_experience': 59, 'type': 'water'}, {'name': 'seadra', 'height': 12, 'weight': 250, 'base_experience': 154, 'type': 'water'}, {'name': 'goldeen', 'height': 6, 'weight': 150, 'base_experience': 64, 'type': 'water'}, {'name': 'seaking', 'height': 13, 'weight': 390, 'base_experience': 158, 'type': 'water'}, {'name': 'staryu', 'height': 8, 'weight': 345, 'base_experience': 68, 'type': 'water'}, {'name': 'starmie', 'height': 11, 'weight': 800, 'base_experience': 182, 'type': 'water'}, {'name': 'mr-mime', 'height': 13, 'weight': 545, 'base_experience': 161, 'type': 'psychic'}, {'name': 'scyther', 'height': 15, 'weight': 560, 'base_experience': 100, 'type': 'bug'}, {'name': 'jynx', 'height': 14, 'weight': 406, 'base_experience': 159, 'type': 'ice'}, {'name': 'electabuzz', 'height': 11, 'weight': 300, 'base_experience': 172, 'type': 'electric'}, {'name': 'magmar', 'height': 13, 'weight': 445, 'base_experience': 173, 'type': 'fire'}, {'name': 'pinsir', 'height': 15, 'weight': 550, 'base_experience': 175, 'type': 'bug'}, {'name': 'tauros', 'height': 14, 'weight': 884, 'base_experience': 172, 'type': 'normal'}, {'name': 'magikarp', 'height': 9, 'weight': 100, 'base_experience': 40, 'type': 'water'}, {'name': 'gyarados', 'height': 65, 'weight': 2350, 'base_experience': 189, 'type': 'water'}, {'name': 'lapras', 'height': 25, 'weight': 2200, 'base_experience': 187, 'type': 'water'}, {'name': 'ditto', 'height': 3, 'weight': 40, 'base_experience': 101, 'type': 'normal'}, {'name': 'eevee', 'height': 3, 'weight': 65, 'base_experience': 65, 'type': 'normal'}, {'name': 'vaporeon', 'height': 10, 'weight': 290, 'base_experience': 184, 'type': 'water'}, {'name': 'jolteon', 'height': 8, 'weight': 245, 'base_experience': 184, 'type': 'electric'}, {'name': 'flareon', 'height': 9, 'weight': 250, 'base_experience': 184, 'type': 'fire'}, {'name': 'porygon', 'height': 8, 'weight': 365, 'base_experience': 79, 'type': 'normal'}, {'name': 'omanyte', 'height': 4, 'weight': 75, 'base_experience': 71, 'type': 'rock'}, {'name': 'omastar', 'height': 10, 'weight': 350, 'base_experience': 173, 'type': 'rock'}, {'name': 'kabuto', 'height': 5, 'weight': 115, 'base_experience': 71, 'type': 'rock'}, {'name': 'kabutops', 'height': 13, 'weight': 405, 'base_experience': 173, 'type': 'rock'}, {'name': 'aerodactyl', 'height': 18, 'weight': 590, 'base_experience': 180, 'type': 'rock'}, {'name': 'snorlax', 'height': 21, 'weight': 4600, 'base_experience': 189, 'type': 'normal'}, {'name': 'articuno', 'height': 17, 'weight': 554, 'base_experience': 261, 'type': 'ice'}, {'name': 'zapdos', 'height': 16, 'weight': 526, 'base_experience': 261, 'type': 'electric'}, {'name': 'moltres', 'height': 20, 'weight': 600, 'base_experience': 261, 'type': 'fire'}, {'name': 'dratini', 'height': 18, 'weight': 33, 'base_experience': 60, 'type': 'dragon'}, {'name': 'dragonair', 'height': 40, 'weight': 165, 'base_experience': 147, 'type': 'dragon'}, {'name': 'dragonite', 'height': 22, 'weight': 2100, 'base_experience': 270, 'type': 'dragon'}, {'name': 'mewtwo', 'height': 20, 'weight': 1220, 'base_experience': 306, 'type': 'psychic'}]

In [23]:
poke_list

[{'name': 'bulbasaur',
  'height': 7,
  'weight': 69,
  'base_experience': 64,
  'type': 'grass'},
 {'name': 'ivysaur',
  'height': 10,
  'weight': 130,
  'base_experience': 142,
  'type': 'grass'},
 {'name': 'venusaur',
  'height': 20,
  'weight': 1000,
  'base_experience': 236,
  'type': 'grass'},
 {'name': 'charmander',
  'height': 6,
  'weight': 85,
  'base_experience': 62,
  'type': 'fire'},
 {'name': 'charmeleon',
  'height': 11,
  'weight': 190,
  'base_experience': 142,
  'type': 'fire'},
 {'name': 'charizard',
  'height': 17,
  'weight': 905,
  'base_experience': 240,
  'type': 'fire'},
 {'name': 'squirtle',
  'height': 5,
  'weight': 90,
  'base_experience': 63,
  'type': 'water'},
 {'name': 'wartortle',
  'height': 10,
  'weight': 225,
  'base_experience': 142,
  'type': 'water'},
 {'name': 'blastoise',
  'height': 16,
  'weight': 855,
  'base_experience': 239,
  'type': 'water'},
 {'name': 'caterpie',
  'height': 3,
  'weight': 29,
  'base_experience': 39,
  'type': 'bug'},
 {'name': 'metapod',
  'height': 7,
  'weight': 99,
  'base_experience': 72,
  'type': 'bug'},
 {'name': 'butterfree',
  'height': 11,
  'weight': 320,
  'base_experience': 178,
  'type': 'bug'},
 {'name': 'weedle',
  'height': 3,
  'weight': 32,
  'base_experience': 39,
  'type': 'bug'},
 {'name': 'kakuna',
  'height': 6,
  'weight': 100,
  'base_experience': 72,
  'type': 'bug'},
 {'name': 'beedrill',
  'height': 10,
  'weight': 295,
  'base_experience': 178,
  'type': 'bug'},
 {'name': 'pidgey',
  'height': 3,
  'weight': 18,
  'base_experience': 50,
  'type': 'normal'},
 {'name': 'pidgeotto',
  'height': 11,
  'weight': 300,
  'base_experience': 122,
  'type': 'normal'},
 {'name': 'pidgeot',
  'height': 15,
  'weight': 395,
  'base_experience': 216,
  'type': 'normal'},
 {'name': 'rattata',
  'height': 3,
  'weight': 35,
  'base_experience': 51,
  'type': 'normal'},
 {'name': 'raticate',
  'height': 7,
  'weight': 185,
  'base_experience': 145,
  'type': 'normal'},
 {'name': 'spearow',
  'height': 3,
  'weight': 20,
  'base_experience': 52,
  'type': 'normal'},
 {'name': 'fearow',
  'height': 12,
  'weight': 380,
  'base_experience': 155,
  'type': 'normal'},
 {'name': 'ekans',
  'height': 20,
  'weight': 69,
  'base_experience': 58,
  'type': 'poison'},
 {'name': 'arbok',
  'height': 35,
  'weight': 650,
  'base_experience': 157,
  'type': 'poison'},
 {'name': 'pikachu',
  'height': 4,
  'weight': 60,
  'base_experience': 112,
  'type': 'electric'},
 {'name': 'raichu',
  'height': 8,
  'weight': 300,
  'base_experience': 218,
  'type': 'electric'},
 {'name': 'sandshrew',
  'height': 6,
  'weight': 120,
  'base_experience': 60,
  'type': 'ground'},
 {'name': 'sandslash',
  'height': 10,
  'weight': 295,
  'base_experience': 158,
  'type': 'ground'},
 {'name': 'nidoran-f',
  'height': 4,
  'weight': 70,
  'base_experience': 55,
  'type': 'poison'},
 {'name': 'nidorina',
  'height': 8,
  'weight': 200,
  'base_experience': 128,
  'type': 'poison'},
 {'name': 'nidoqueen',
  'height': 13,
  'weight': 600,
  'base_experience': 227,
  'type': 'poison'},
 {'name': 'nidoran-m',
  'height': 5,
  'weight': 90,
  'base_experience': 55,
  'type': 'poison'},
 {'name': 'nidorino',
  'height': 9,
  'weight': 195,
  'base_experience': 128,
  'type': 'poison'},
 {'name': 'nidoking',
  'height': 14,
  'weight': 620,
  'base_experience': 227,
  'type': 'poison'},
 {'name': 'clefairy',
  'height': 6,
  'weight': 75,
  'base_experience': 113,
  'type': 'fairy'},
 {'name': 'clefable',
  'height': 13,
  'weight': 400,
  'base_experience': 217,
  'type': 'fairy'},
 {'name': 'vulpix',
  'height': 6,
  'weight': 99,
  'base_experience': 60,
  'type': 'fire'},
 {'name': 'ninetales',
  'height': 11,
  'weight': 199,
  'base_experience': 177,
  'type': 'fire'},
 {'name': 'jigglypuff',
  'height': 5,
  'weight': 55,
  'base_experience': 95,
  'type': 'normal'},
 {'name': 'wigglytuff',
  'height': 10,
  'weight': 120,
  'base_experience': 196,
  'type': 'normal'},
 {'name': 'zubat',
  'height': 8,
  'weight': 75,
  'base_experience': 49,
  'type': 'poison'},
 {'name': 'golbat',
  'height': 16,
  'weight': 550,
  'base_experience': 159,
  'type': 'poison'},
 {'name': 'oddish',
  'height': 5,
  'weight': 54,
  'base_experience': 64,
  'type': 'grass'},
 {'name': 'gloom',
  'height': 8,
  'weight': 86,
  'base_experience': 138,
  'type': 'grass'},
 {'name': 'vileplume',
  'height': 12,
  'weight': 186,
  'base_experience': 221,
  'type': 'grass'},
 {'name': 'paras',
  'height': 3,
  'weight': 54,
  'base_experience': 57,
  'type': 'bug'},
 {'name': 'parasect',
  'height': 10,
  'weight': 295,
  'base_experience': 142,
  'type': 'bug'},
 {'name': 'venonat',
  'height': 10,
  'weight': 300,
  'base_experience': 61,
  'type': 'bug'},
 {'name': 'venomoth',
  'height': 15,
  'weight': 125,
  'base_experience': 158,
  'type': 'bug'},
 {'name': 'diglett',
  'height': 2,
  'weight': 8,
  'base_experience': 53,
  'type': 'ground'},
 {'name': 'dugtrio',
  'height': 7,
  'weight': 333,
  'base_experience': 149,
  'type': 'ground'},
 {'name': 'meowth',
  'height': 4,
  'weight': 42,
  'base_experience': 58,
  'type': 'normal'},
 {'name': 'persian',
  'height': 10,
  'weight': 320,
  'base_experience': 154,
  'type': 'normal'},
 {'name': 'psyduck',
  'height': 8,
  'weight': 196,
  'base_experience': 64,
  'type': 'water'},
 {'name': 'golduck',
  'height': 17,
  'weight': 766,
  'base_experience': 175,
  'type': 'water'},
 {'name': 'mankey',
  'height': 5,
  'weight': 280,
  'base_experience': 61,
  'type': 'fighting'},
 {'name': 'primeape',
  'height': 10,
  'weight': 320,
  'base_experience': 159,
  'type': 'fighting'},
 {'name': 'growlithe',
  'height': 7,
  'weight': 190,
  'base_experience': 70,
  'type': 'fire'},
 {'name': 'arcanine',
  'height': 19,
  'weight': 1550,
  'base_experience': 194,
  'type': 'fire'},
 {'name': 'poliwag',
  'height': 6,
  'weight': 124,
  'base_experience': 60,
  'type': 'water'},
 {'name': 'poliwhirl',
  'height': 10,
  'weight': 200,
  'base_experience': 135,
  'type': 'water'},
 {'name': 'poliwrath',
  'height': 13,
  'weight': 540,
  'base_experience': 230,
  'type': 'water'},
 {'name': 'abra',
  'height': 9,
  'weight': 195,
  'base_experience': 62,
  'type': 'psychic'},
 {'name': 'kadabra',
  'height': 13,
  'weight': 565,
  'base_experience': 140,
  'type': 'psychic'},
 {'name': 'alakazam',
  'height': 15,
  'weight': 480,
  'base_experience': 225,
  'type': 'psychic'},
 {'name': 'machop',
  'height': 8,
  'weight': 195,
  'base_experience': 61,
  'type': 'fighting'},
 {'name': 'machoke',
  'height': 15,
  'weight': 705,
  'base_experience': 142,
  'type': 'fighting'},
 {'name': 'machamp',
  'height': 16,
  'weight': 1300,
  'base_experience': 227,
  'type': 'fighting'},
 {'name': 'bellsprout',
  'height': 7,
  'weight': 40,
  'base_experience': 60,
  'type': 'grass'},
 {'name': 'weepinbell',
  'height': 10,
  'weight': 64,
  'base_experience': 137,
  'type': 'grass'},
 {'name': 'victreebel',
  'height': 17,
  'weight': 155,
  'base_experience': 221,
  'type': 'grass'},
 {'name': 'tentacool',
  'height': 9,
  'weight': 455,
  'base_experience': 67,
  'type': 'water'},
 {'name': 'tentacruel',
  'height': 16,
  'weight': 550,
  'base_experience': 180,
  'type': 'water'},
 {'name': 'geodude',
  'height': 4,
  'weight': 200,
  'base_experience': 60,
  'type': 'rock'},
 {'name': 'graveler',
  'height': 10,
  'weight': 1050,
  'base_experience': 137,
  'type': 'rock'},
 {'name': 'golem',
  'height': 14,
  'weight': 3000,
  'base_experience': 223,
  'type': 'rock'},
 {'name': 'ponyta',
  'height': 10,
  'weight': 300,
  'base_experience': 82,
  'type': 'fire'},
 {'name': 'rapidash',
  'height': 17,
  'weight': 950,
  'base_experience': 175,
  'type': 'fire'},
 {'name': 'slowpoke',
  'height': 12,
  'weight': 360,
  'base_experience': 63,
  'type': 'water'},
 {'name': 'slowbro',
  'height': 16,
  'weight': 785,
  'base_experience': 172,
  'type': 'water'},
 {'name': 'magnemite',
  'height': 3,
  'weight': 60,
  'base_experience': 65,
  'type': 'electric'},
 {'name': 'magneton',
  'height': 10,
  'weight': 600,
  'base_experience': 163,
  'type': 'electric'},
 {'name': 'farfetchd',
  'height': 8,
  'weight': 150,
  'base_experience': 132,
  'type': 'normal'},
 {'name': 'doduo',
  'height': 14,
  'weight': 392,
  'base_experience': 62,
  'type': 'normal'},
 {'name': 'dodrio',
  'height': 18,
  'weight': 852,
  'base_experience': 165,
  'type': 'normal'},
 {'name': 'seel',
  'height': 11,
  'weight': 900,
  'base_experience': 65,
  'type': 'water'},
 {'name': 'dewgong',
  'height': 17,
  'weight': 1200,
  'base_experience': 166,
  'type': 'water'},
 {'name': 'grimer',
  'height': 9,
  'weight': 300,
  'base_experience': 65,
  'type': 'poison'},
 {'name': 'muk',
  'height': 12,
  'weight': 300,
  'base_experience': 175,
  'type': 'poison'},
 {'name': 'shellder',
  'height': 3,
  'weight': 40,
  'base_experience': 61,
  'type': 'water'},
 {'name': 'cloyster',
  'height': 15,
  'weight': 1325,
  'base_experience': 184,
  'type': 'water'},
 {'name': 'gastly',
  'height': 13,
  'weight': 1,
  'base_experience': 62,
  'type': 'ghost'},
 {'name': 'haunter',
  'height': 16,
  'weight': 1,
  'base_experience': 142,
  'type': 'ghost'},
 {'name': 'gengar',
  'height': 15,
  'weight': 405,
  'base_experience': 225,
  'type': 'ghost'},
 {'name': 'onix',
  'height': 88,
  'weight': 2100,
  'base_experience': 77,
  'type': 'rock'},
 {'name': 'drowzee',
  'height': 10,
  'weight': 324,
  'base_experience': 66,
  'type': 'psychic'},
 {'name': 'hypno',
  'height': 16,
  'weight': 756,
  'base_experience': 169,
  'type': 'psychic'},
 {'name': 'krabby',
  'height': 4,
  'weight': 65,
  'base_experience': 65,
  'type': 'water'},
 {'name': 'kingler',
  'height': 13,
  'weight': 600,
  'base_experience': 166,
  'type': 'water'},
 {'name': 'voltorb',
  'height': 5,
  'weight': 104,
  'base_experience': 66,
  'type': 'electric'},
 {'name': 'electrode',
  'height': 12,
  'weight': 666,
  'base_experience': 172,
  'type': 'electric'},
 {'name': 'exeggcute',
  'height': 4,
  'weight': 25,
  'base_experience': 65,
  'type': 'grass'},
 {'name': 'exeggutor',
  'height': 20,
  'weight': 1200,
  'base_experience': 186,
  'type': 'grass'},
 {'name': 'cubone',
  'height': 4,
  'weight': 65,
  'base_experience': 64,
  'type': 'ground'},
 {'name': 'marowak',
  'height': 10,
  'weight': 450,
  'base_experience': 149,
  'type': 'ground'},
 {'name': 'hitmonlee',
  'height': 15,
  'weight': 498,
  'base_experience': 159,
  'type': 'fighting'},
 {'name': 'hitmonchan',
  'height': 14,
  'weight': 502,
  'base_experience': 159,
  'type': 'fighting'},
 {'name': 'lickitung',
  'height': 12,
  'weight': 655,
  'base_experience': 77,
  'type': 'normal'},
 {'name': 'koffing',
  'height': 6,
  'weight': 10,
  'base_experience': 68,
  'type': 'poison'},
 {'name': 'weezing',
  'height': 12,
  'weight': 95,
  'base_experience': 172,
  'type': 'poison'},
 {'name': 'rhyhorn',
  'height': 10,
  'weight': 1150,
  'base_experience': 69,
  'type': 'ground'},
 {'name': 'rhydon',
  'height': 19,
  'weight': 1200,
  'base_experience': 170,
  'type': 'ground'},
 {'name': 'chansey',
  'height': 11,
  'weight': 346,
  'base_experience': 395,
  'type': 'normal'},
 {'name': 'tangela',
  'height': 10,
  'weight': 350,
  'base_experience': 87,
  'type': 'grass'},
 {'name': 'kangaskhan',
  'height': 22,
  'weight': 800,
  'base_experience': 172,
  'type': 'normal'},
 {'name': 'horsea',
  'height': 4,
  'weight': 80,
  'base_experience': 59,
  'type': 'water'},
 {'name': 'seadra',
  'height': 12,
  'weight': 250,
  'base_experience': 154,
  'type': 'water'},
 {'name': 'goldeen',
  'height': 6,
  'weight': 150,
  'base_experience': 64,
  'type': 'water'},
 {'name': 'seaking',
  'height': 13,
  'weight': 390,
  'base_experience': 158,
  'type': 'water'},
 {'name': 'staryu',
  'height': 8,
  'weight': 345,
  'base_experience': 68,
  'type': 'water'},
 {'name': 'starmie',
  'height': 11,
  'weight': 800,
  'base_experience': 182,
  'type': 'water'},
 {'name': 'mr-mime',
  'height': 13,
  'weight': 545,
  'base_experience': 161,
  'type': 'psychic'},
 {'name': 'scyther',
  'height': 15,
  'weight': 560,
  'base_experience': 100,
  'type': 'bug'},
 {'name': 'jynx',
  'height': 14,
  'weight': 406,
  'base_experience': 159,
  'type': 'ice'},
 {'name': 'electabuzz',
  'height': 11,
  'weight': 300,
  'base_experience': 172,
  'type': 'electric'},
 {'name': 'magmar',
  'height': 13,
  'weight': 445,
  'base_experience': 173,
  'type': 'fire'},
 {'name': 'pinsir',
  'height': 15,
  'weight': 550,
  'base_experience': 175,
  'type': 'bug'},
 {'name': 'tauros',
  'height': 14,
  'weight': 884,
  'base_experience': 172,
  'type': 'normal'},
 {'name': 'magikarp',
  'height': 9,
  'weight': 100,
  'base_experience': 40,
  'type': 'water'},
 {'name': 'gyarados',
  'height': 65,
  'weight': 2350,
  'base_experience': 189,
  'type': 'water'},
 {'name': 'lapras',
  'height': 25,
  'weight': 2200,
  'base_experience': 187,
  'type': 'water'},
 {'name': 'ditto',
  'height': 3,
  'weight': 40,
  'base_experience': 101,
  'type': 'normal'},
 {'name': 'eevee',
  'height': 3,
  'weight': 65,
  'base_experience': 65,
  'type': 'normal'},
 {'name': 'vaporeon',
  'height': 10,
  'weight': 290,
  'base_experience': 184,
  'type': 'water'},
 {'name': 'jolteon',
  'height': 8,
  'weight': 245,
  'base_experience': 184,
  'type': 'electric'},
 {'name': 'flareon',
  'height': 9,
  'weight': 250,
  'base_experience': 184,
  'type': 'fire'},
 {'name': 'porygon',
  'height': 8,
  'weight': 365,
  'base_experience': 79,
  'type': 'normal'},
 {'name': 'omanyte',
  'height': 4,
  'weight': 75,
  'base_experience': 71,
  'type': 'rock'},
 {'name': 'omastar',
  'height': 10,
  'weight': 350,
  'base_experience': 173,
  'type': 'rock'},
 {'name': 'kabuto',
  'height': 5,
  'weight': 115,
  'base_experience': 71,
  'type': 'rock'},
 {'name': 'kabutops',
  'height': 13,
  'weight': 405,
  'base_experience': 173,
  'type': 'rock'},
 {'name': 'aerodactyl',
  'height': 18,
  'weight': 590,
  'base_experience': 180,
  'type': 'rock'},
 {'name': 'snorlax',
  'height': 21,
  'weight': 4600,
  'base_experience': 189,
  'type': 'normal'},
 {'name': 'articuno',
  'height': 17,
  'weight': 554,
  'base_experience': 261,
  'type': 'ice'},
 {'name': 'zapdos',
  'height': 16,
  'weight': 526,
  'base_experience': 261,
  'type': 'electric'},
 {'name': 'moltres',
  'height': 20,
  'weight': 600,
  'base_experience': 261,
  'type': 'fire'},
 {'name': 'dratini',
  'height': 18,
  'weight': 33,
  'base_experience': 60,
  'type': 'dragon'},
 {'name': 'dragonair',
  'height': 40,
  'weight': 165,
  'base_experience': 147,
  'type': 'dragon'},
 {'name': 'dragonite',
  'height': 22,
  'weight': 2100,
  'base_experience': 270,
  'type': 'dragon'},
 {'name': 'mewtwo',
  'height': 20,
  'weight': 1220,
  'base_experience': 306,
  'type': 'psychic'}]

In [11]:
data.keys()

dict_keys(['abilities', 'base_experience', 'cries', 'forms', 'game_indices', 'height', 'held_items', 'id', 'is_default', 'location_area_encounters', 'moves', 'name', 'order', 'past_abilities', 'past_stats', 'past_types', 'species', 'sprites', 'stats', 'types', 'weight'])

## Tasks

1. Using the example above, get data for Pokémon IDs from 1 to 151

2. Extract:
   - name
   - height
   - weight
   - base_experience
   - first type

3. Create a DataFrame

4. Add a new column:
   - weight_kg (divide weight by 10)

5. Answer:
   - Which Pokémon is the heaviest?
   - What is the average weight?
   - How many Pokémon are there per type?

6. Answer:
   - Which type has the highest average weight?

In [28]:
# Your code goes here
import pandas as pd
import requests

poke_list = []

for id in range(1, 152):
    url = f"https://pokeapi.co/api/v2/pokemon/{id}"
    response = requests.get(url)
    data = response.json()

    poke_type = data["types"][0]["type"]["name"]

    poke_list.append({
        "name": data["name"],
        "height": data["height"],
        "weight": data["weight"],
        "base_experience": data["base_experience"],
        "type": poke_type
    })

print(poke_list)

df = pd.DataFrame(poke_list)

print(df)

[{'name': 'bulbasaur', 'height': 7, 'weight': 69, 'base_experience': 64, 'type': 'grass'}, {'name': 'ivysaur', 'height': 10, 'weight': 130, 'base_experience': 142, 'type': 'grass'}, {'name': 'venusaur', 'height': 20, 'weight': 1000, 'base_experience': 236, 'type': 'grass'}, {'name': 'charmander', 'height': 6, 'weight': 85, 'base_experience': 62, 'type': 'fire'}, {'name': 'charmeleon', 'height': 11, 'weight': 190, 'base_experience': 142, 'type': 'fire'}, {'name': 'charizard', 'height': 17, 'weight': 905, 'base_experience': 240, 'type': 'fire'}, {'name': 'squirtle', 'height': 5, 'weight': 90, 'base_experience': 63, 'type': 'water'}, {'name': 'wartortle', 'height': 10, 'weight': 225, 'base_experience': 142, 'type': 'water'}, {'name': 'blastoise', 'height': 16, 'weight': 855, 'base_experience': 239, 'type': 'water'}, {'name': 'caterpie', 'height': 3, 'weight': 29, 'base_experience': 39, 'type': 'bug'}, {'name': 'metapod', 'height': 7, 'weight': 99, 'base_experience': 72, 'type': 'bug'}, {'name': 'butterfree', 'height': 11, 'weight': 320, 'base_experience': 178, 'type': 'bug'}, {'name': 'weedle', 'height': 3, 'weight': 32, 'base_experience': 39, 'type': 'bug'}, {'name': 'kakuna', 'height': 6, 'weight': 100, 'base_experience': 72, 'type': 'bug'}, {'name': 'beedrill', 'height': 10, 'weight': 295, 'base_experience': 178, 'type': 'bug'}, {'name': 'pidgey', 'height': 3, 'weight': 18, 'base_experience': 50, 'type': 'normal'}, {'name': 'pidgeotto', 'height': 11, 'weight': 300, 'base_experience': 122, 'type': 'normal'}, {'name': 'pidgeot', 'height': 15, 'weight': 395, 'base_experience': 216, 'type': 'normal'}, {'name': 'rattata', 'height': 3, 'weight': 35, 'base_experience': 51, 'type': 'normal'}, {'name': 'raticate', 'height': 7, 'weight': 185, 'base_experience': 145, 'type': 'normal'}, {'name': 'spearow', 'height': 3, 'weight': 20, 'base_experience': 52, 'type': 'normal'}, {'name': 'fearow', 'height': 12, 'weight': 380, 'base_experience': 155, 'type': 'normal'}, {'name': 'ekans', 'height': 20, 'weight': 69, 'base_experience': 58, 'type': 'poison'}, {'name': 'arbok', 'height': 35, 'weight': 650, 'base_experience': 157, 'type': 'poison'}, {'name': 'pikachu', 'height': 4, 'weight': 60, 'base_experience': 112, 'type': 'electric'}, {'name': 'raichu', 'height': 8, 'weight': 300, 'base_experience': 218, 'type': 'electric'}, {'name': 'sandshrew', 'height': 6, 'weight': 120, 'base_experience': 60, 'type': 'ground'}, {'name': 'sandslash', 'height': 10, 'weight': 295, 'base_experience': 158, 'type': 'ground'}, {'name': 'nidoran-f', 'height': 4, 'weight': 70, 'base_experience': 55, 'type': 'poison'}, {'name': 'nidorina', 'height': 8, 'weight': 200, 'base_experience': 128, 'type': 'poison'}, {'name': 'nidoqueen', 'height': 13, 'weight': 600, 'base_experience': 227, 'type': 'poison'}, {'name': 'nidoran-m', 'height': 5, 'weight': 90, 'base_experience': 55, 'type': 'poison'}, {'name': 'nidorino', 'height': 9, 'weight': 195, 'base_experience': 128, 'type': 'poison'}, {'name': 'nidoking', 'height': 14, 'weight': 620, 'base_experience': 227, 'type': 'poison'}, {'name': 'clefairy', 'height': 6, 'weight': 75, 'base_experience': 113, 'type': 'fairy'}, {'name': 'clefable', 'height': 13, 'weight': 400, 'base_experience': 217, 'type': 'fairy'}, {'name': 'vulpix', 'height': 6, 'weight': 99, 'base_experience': 60, 'type': 'fire'}, {'name': 'ninetales', 'height': 11, 'weight': 199, 'base_experience': 177, 'type': 'fire'}, {'name': 'jigglypuff', 'height': 5, 'weight': 55, 'base_experience': 95, 'type': 'normal'}, {'name': 'wigglytuff', 'height': 10, 'weight': 120, 'base_experience': 196, 'type': 'normal'}, {'name': 'zubat', 'height': 8, 'weight': 75, 'base_experience': 49, 'type': 'poison'}, {'name': 'golbat', 'height': 16, 'weight': 550, 'base_experience': 159, 'type': 'poison'}, {'name': 'oddish', 'height': 5, 'weight': 54, 'base_experience': 64, 'type': 'grass'}, {'name': 'gloom', 'height': 8, 'weight': 86, 'base_experience': 138, 'type': 'grass'}, {'name': 'vileplume', 'height': 12, 'weight': 186, 'base_experience': 221, 'type': 'grass'}, {'name': 'paras', 'height': 3, 'weight': 54, 'base_experience': 57, 'type': 'bug'}, {'name': 'parasect', 'height': 10, 'weight': 295, 'base_experience': 142, 'type': 'bug'}, {'name': 'venonat', 'height': 10, 'weight': 300, 'base_experience': 61, 'type': 'bug'}, {'name': 'venomoth', 'height': 15, 'weight': 125, 'base_experience': 158, 'type': 'bug'}, {'name': 'diglett', 'height': 2, 'weight': 8, 'base_experience': 53, 'type': 'ground'}, {'name': 'dugtrio', 'height': 7, 'weight': 333, 'base_experience': 149, 'type': 'ground'}, {'name': 'meowth', 'height': 4, 'weight': 42, 'base_experience': 58, 'type': 'normal'}, {'name': 'persian', 'height': 10, 'weight': 320, 'base_experience': 154, 'type': 'normal'}, {'name': 'psyduck', 'height': 8, 'weight': 196, 'base_experience': 64, 'type': 'water'}, {'name': 'golduck', 'height': 17, 'weight': 766, 'base_experience': 175, 'type': 'water'}, {'name': 'mankey', 'height': 5, 'weight': 280, 'base_experience': 61, 'type': 'fighting'}, {'name': 'primeape', 'height': 10, 'weight': 320, 'base_experience': 159, 'type': 'fighting'}, {'name': 'growlithe', 'height': 7, 'weight': 190, 'base_experience': 70, 'type': 'fire'}, {'name': 'arcanine', 'height': 19, 'weight': 1550, 'base_experience': 194, 'type': 'fire'}, {'name': 'poliwag', 'height': 6, 'weight': 124, 'base_experience': 60, 'type': 'water'}, {'name': 'poliwhirl', 'height': 10, 'weight': 200, 'base_experience': 135, 'type': 'water'}, {'name': 'poliwrath', 'height': 13, 'weight': 540, 'base_experience': 230, 'type': 'water'}, {'name': 'abra', 'height': 9, 'weight': 195, 'base_experience': 62, 'type': 'psychic'}, {'name': 'kadabra', 'height': 13, 'weight': 565, 'base_experience': 140, 'type': 'psychic'}, {'name': 'alakazam', 'height': 15, 'weight': 480, 'base_experience': 225, 'type': 'psychic'}, {'name': 'machop', 'height': 8, 'weight': 195, 'base_experience': 61, 'type': 'fighting'}, {'name': 'machoke', 'height': 15, 'weight': 705, 'base_experience': 142, 'type': 'fighting'}, {'name': 'machamp', 'height': 16, 'weight': 1300, 'base_experience': 227, 'type': 'fighting'}, {'name': 'bellsprout', 'height': 7, 'weight': 40, 'base_experience': 60, 'type': 'grass'}, {'name': 'weepinbell', 'height': 10, 'weight': 64, 'base_experience': 137, 'type': 'grass'}, {'name': 'victreebel', 'height': 17, 'weight': 155, 'base_experience': 221, 'type': 'grass'}, {'name': 'tentacool', 'height': 9, 'weight': 455, 'base_experience': 67, 'type': 'water'}, {'name': 'tentacruel', 'height': 16, 'weight': 550, 'base_experience': 180, 'type': 'water'}, {'name': 'geodude', 'height': 4, 'weight': 200, 'base_experience': 60, 'type': 'rock'}, {'name': 'graveler', 'height': 10, 'weight': 1050, 'base_experience': 137, 'type': 'rock'}, {'name': 'golem', 'height': 14, 'weight': 3000, 'base_experience': 223, 'type': 'rock'}, {'name': 'ponyta', 'height': 10, 'weight': 300, 'base_experience': 82, 'type': 'fire'}, {'name': 'rapidash', 'height': 17, 'weight': 950, 'base_experience': 175, 'type': 'fire'}, {'name': 'slowpoke', 'height': 12, 'weight': 360, 'base_experience': 63, 'type': 'water'}, {'name': 'slowbro', 'height': 16, 'weight': 785, 'base_experience': 172, 'type': 'water'}, {'name': 'magnemite', 'height': 3, 'weight': 60, 'base_experience': 65, 'type': 'electric'}, {'name': 'magneton', 'height': 10, 'weight': 600, 'base_experience': 163, 'type': 'electric'}, {'name': 'farfetchd', 'height': 8, 'weight': 150, 'base_experience': 132, 'type': 'normal'}, {'name': 'doduo', 'height': 14, 'weight': 392, 'base_experience': 62, 'type': 'normal'}, {'name': 'dodrio', 'height': 18, 'weight': 852, 'base_experience': 165, 'type': 'normal'}, {'name': 'seel', 'height': 11, 'weight': 900, 'base_experience': 65, 'type': 'water'}, {'name': 'dewgong', 'height': 17, 'weight': 1200, 'base_experience': 166, 'type': 'water'}, {'name': 'grimer', 'height': 9, 'weight': 300, 'base_experience': 65, 'type': 'poison'}, {'name': 'muk', 'height': 12, 'weight': 300, 'base_experience': 175, 'type': 'poison'}, {'name': 'shellder', 'height': 3, 'weight': 40, 'base_experience': 61, 'type': 'water'}, {'name': 'cloyster', 'height': 15, 'weight': 1325, 'base_experience': 184, 'type': 'water'}, {'name': 'gastly', 'height': 13, 'weight': 1, 'base_experience': 62, 'type': 'ghost'}, {'name': 'haunter', 'height': 16, 'weight': 1, 'base_experience': 142, 'type': 'ghost'}, {'name': 'gengar', 'height': 15, 'weight': 405, 'base_experience': 225, 'type': 'ghost'}, {'name': 'onix', 'height': 88, 'weight': 2100, 'base_experience': 77, 'type': 'rock'}, {'name': 'drowzee', 'height': 10, 'weight': 324, 'base_experience': 66, 'type': 'psychic'}, {'name': 'hypno', 'height': 16, 'weight': 756, 'base_experience': 169, 'type': 'psychic'}, {'name': 'krabby', 'height': 4, 'weight': 65, 'base_experience': 65, 'type': 'water'}, {'name': 'kingler', 'height': 13, 'weight': 600, 'base_experience': 166, 'type': 'water'}, {'name': 'voltorb', 'height': 5, 'weight': 104, 'base_experience': 66, 'type': 'electric'}, {'name': 'electrode', 'height': 12, 'weight': 666, 'base_experience': 172, 'type': 'electric'}, {'name': 'exeggcute', 'height': 4, 'weight': 25, 'base_experience': 65, 'type': 'grass'}, {'name': 'exeggutor', 'height': 20, 'weight': 1200, 'base_experience': 186, 'type': 'grass'}, {'name': 'cubone', 'height': 4, 'weight': 65, 'base_experience': 64, 'type': 'ground'}, {'name': 'marowak', 'height': 10, 'weight': 450, 'base_experience': 149, 'type': 'ground'}, {'name': 'hitmonlee', 'height': 15, 'weight': 498, 'base_experience': 159, 'type': 'fighting'}, {'name': 'hitmonchan', 'height': 14, 'weight': 502, 'base_experience': 159, 'type': 'fighting'}, {'name': 'lickitung', 'height': 12, 'weight': 655, 'base_experience': 77, 'type': 'normal'}, {'name': 'koffing', 'height': 6, 'weight': 10, 'base_experience': 68, 'type': 'poison'}, {'name': 'weezing', 'height': 12, 'weight': 95, 'base_experience': 172, 'type': 'poison'}, {'name': 'rhyhorn', 'height': 10, 'weight': 1150, 'base_experience': 69, 'type': 'ground'}, {'name': 'rhydon', 'height': 19, 'weight': 1200, 'base_experience': 170, 'type': 'ground'}, {'name': 'chansey', 'height': 11, 'weight': 346, 'base_experience': 395, 'type': 'normal'}, {'name': 'tangela', 'height': 10, 'weight': 350, 'base_experience': 87, 'type': 'grass'}, {'name': 'kangaskhan', 'height': 22, 'weight': 800, 'base_experience': 172, 'type': 'normal'}, {'name': 'horsea', 'height': 4, 'weight': 80, 'base_experience': 59, 'type': 'water'}, {'name': 'seadra', 'height': 12, 'weight': 250, 'base_experience': 154, 'type': 'water'}, {'name': 'goldeen', 'height': 6, 'weight': 150, 'base_experience': 64, 'type': 'water'}, {'name': 'seaking', 'height': 13, 'weight': 390, 'base_experience': 158, 'type': 'water'}, {'name': 'staryu', 'height': 8, 'weight': 345, 'base_experience': 68, 'type': 'water'}, {'name': 'starmie', 'height': 11, 'weight': 800, 'base_experience': 182, 'type': 'water'}, {'name': 'mr-mime', 'height': 13, 'weight': 545, 'base_experience': 161, 'type': 'psychic'}, {'name': 'scyther', 'height': 15, 'weight': 560, 'base_experience': 100, 'type': 'bug'}, {'name': 'jynx', 'height': 14, 'weight': 406, 'base_experience': 159, 'type': 'ice'}, {'name': 'electabuzz', 'height': 11, 'weight': 300, 'base_experience': 172, 'type': 'electric'}, {'name': 'magmar', 'height': 13, 'weight': 445, 'base_experience': 173, 'type': 'fire'}, {'name': 'pinsir', 'height': 15, 'weight': 550, 'base_experience': 175, 'type': 'bug'}, {'name': 'tauros', 'height': 14, 'weight': 884, 'base_experience': 172, 'type': 'normal'}, {'name': 'magikarp', 'height': 9, 'weight': 100, 'base_experience': 40, 'type': 'water'}, {'name': 'gyarados', 'height': 65, 'weight': 2350, 'base_experience': 189, 'type': 'water'}, {'name': 'lapras', 'height': 25, 'weight': 2200, 'base_experience': 187, 'type': 'water'}, {'name': 'ditto', 'height': 3, 'weight': 40, 'base_experience': 101, 'type': 'normal'}, {'name': 'eevee', 'height': 3, 'weight': 65, 'base_experience': 65, 'type': 'normal'}, {'name': 'vaporeon', 'height': 10, 'weight': 290, 'base_experience': 184, 'type': 'water'}, {'name': 'jolteon', 'height': 8, 'weight': 245, 'base_experience': 184, 'type': 'electric'}, {'name': 'flareon', 'height': 9, 'weight': 250, 'base_experience': 184, 'type': 'fire'}, {'name': 'porygon', 'height': 8, 'weight': 365, 'base_experience': 79, 'type': 'normal'}, {'name': 'omanyte', 'height': 4, 'weight': 75, 'base_experience': 71, 'type': 'rock'}, {'name': 'omastar', 'height': 10, 'weight': 350, 'base_experience': 173, 'type': 'rock'}, {'name': 'kabuto', 'height': 5, 'weight': 115, 'base_experience': 71, 'type': 'rock'}, {'name': 'kabutops', 'height': 13, 'weight': 405, 'base_experience': 173, 'type': 'rock'}, {'name': 'aerodactyl', 'height': 18, 'weight': 590, 'base_experience': 180, 'type': 'rock'}, {'name': 'snorlax', 'height': 21, 'weight': 4600, 'base_experience': 189, 'type': 'normal'}, {'name': 'articuno', 'height': 17, 'weight': 554, 'base_experience': 261, 'type': 'ice'}, {'name': 'zapdos', 'height': 16, 'weight': 526, 'base_experience': 261, 'type': 'electric'}, {'name': 'moltres', 'height': 20, 'weight': 600, 'base_experience': 261, 'type': 'fire'}, {'name': 'dratini', 'height': 18, 'weight': 33, 'base_experience': 60, 'type': 'dragon'}, {'name': 'dragonair', 'height': 40, 'weight': 165, 'base_experience': 147, 'type': 'dragon'}, {'name': 'dragonite', 'height': 22, 'weight': 2100, 'base_experience': 270, 'type': 'dragon'}, {'name': 'mewtwo', 'height': 20, 'weight': 1220, 'base_experience': 306, 'type': 'psychic'}, {'name': 'mew', 'height': 4, 'weight': 40, 'base_experience': 270, 'type': 'psychic'}]
           name  height  weight  base_experience     type
0     bulbasaur       7      69               64    grass
1       ivysaur      10     130              142    grass
2      venusaur      20    1000              236    grass
3    charmander       6      85               62     fire
4    charmeleon      11     190              142     fire
..          ...     ...     ...              ...      ...
146     dratini      18      33               60   dragon
147   dragonair      40     165              147   dragon
148   dragonite      22    2100              270   dragon
149      mewtwo      20    1220              306  psychic
150         mew       4      40              270  psychic

[151 rows x 5 columns]

# Challenge 2: Crypto Market Analysis

## Goal

Analyze cryptocurrency prices using real-time data.

## Tasks

1. Get prices for:
   - bitcoin
   - ethereum
   - solana
   - dogecoin

2. Convert the response into a DataFrame (coins as rows)

3. Rename columns properly

4. Add:
   - price_rank (ranking by price)
   - price_category:
        - "high" if > 1000  
        - "medium" if between 100 and 1000  
        - "low" if < 100  

5. Answer:
   - Which coin is the most expensive?
   - Which category has more coins?

6. **Bonus**:
   - Create a column with price difference vs bitcoin

In [65]:
# starter code
import requests
import pandas as pd

url = "https://api.coingecko.com/api/v3/simple/price"

params = {
    "ids": "bitcoin,ethereum,solana,dogecoin",
    "vs_currencies": "usd"
}

response = requests.get(url, params=params)
data = response.json()
df = pd.DataFrame(data).T

In [66]:
# Your code goes here
df

                   usd
bitcoin   76200.000000
dogecoin      0.096002
ethereum   2358.500000
solana       86.820000

In [55]:
df = df.rename(columns={"usd": "price_usd"})

In [56]:
df

             price_usd
bitcoin   76135.000000
dogecoin      0.095892
ethereum   2356.010000
solana       86.700000

In [57]:
def categorize(price):
    if price > 1000:
        return "high"
    elif price >= 100:
        return "medium"
    else:
        return "low"

df["price_category"] = df["price_usd"].apply(categorize)

In [58]:
btc_price = df.loc["bitcoin", "price_usd"]
df["diff_vs_bitcoin"] = df["price_usd"] - btc_price

In [60]:
df

             price_usd price_category  diff_vs_bitcoin
bitcoin   76135.000000           high         0.000000
dogecoin      0.095892            low    -76134.904108
ethereum   2356.010000           high    -73778.990000
solana       86.700000            low    -76048.300000

In [62]:
most_expensive = df["price_usd"].idxmax()
most_common_category = df["price_category"].value_counts().idxmax()

print("Most expensive:", most_expensive)
print("Most common category:", most_common_category)

Most expensive: bitcoin
Most common category: high